### ISSUE TITLE
Should test files be moved next to source files ?

### ISSUE THREAD

**Issue by lnfnunes** [mvallim/javascript-collections#13]

**Comment by mvallim** [comment]
Did I not understand the question?

**Comment by lnfnunes** [comment]
@mvallim 
Instead of having a /test folder, test files could be located next to source.
Example:
* This (current)
```
|- src/
....|- main/
........|- hashset.js
....|- test/
........|- hashset.test.js
```
* To this (proposal)
```
|- src/
....|- main/
........|- hashset.js
........|- hashset.test.js
```

**Comment by mvallim** [comment]
I think core and test artifacts should stay in separate packages.

It would be another form that one is accustomed to work, but in my opinion the artifacts must be in different packages.

What do you think?

**Comment by lnfnunes** [comment]
Understood your point!
In a _**project view**_, IMO my option scales better but here we are talking about a _**library**_, so maybe it's better to keep into separate package.
I'm closing this issue! ;-)
