### ISSUE TITLE
Should we convert to isomorphic?

### ISSUE THREAD

**Issue by rmalveis** [mvallim/javascript-collections#4]
My vote is YES, what you think about? 

more about:
http://josdejong.com/blog/2015/03/28/a-broader-view-on-isomorphic-javascript/

**Comment by mvallim** [comment]
YES

**Comment by rmalveis** [comment]
We need to plan how to initiate the lib in both worlds

Em qui, 22 de jun de 2017 09:26, Marcos Tischer Vallim <
notifications@github.com> escreveu:

**Comment by mvallim** [comment]
Do you have any idea, to how?

**Comment by rmalveis** [comment]
Leave this one to me.

**Comment by lnfnunes** [comment]
I used to use/like [this UMD pattern](https://github.com/umdjs/umd/blob/master/templates/returnExports.js)

**Comment by rmalveis** [comment]
@mvallim @lnfnunes 
Update: 
Made it work for node and browser with webpack, but it is not working for AMD. 
I'll try some more tricks and if no result come up I'll share with you and ask for help!

**Comment by lnfnunes** [comment]
Which branch ?

**Comment by rmalveis** [comment]
@mvallim @lnfnunes 

Well... 
Finally it is commited. 

To check everything i changed, please go to commit 2a2f4b45454610e69c1daee2020a9c7cfa276f57

I ended changing a lot of things to get it done. Also I got some extra tools to help us keep quality.

- **Editorconfig** : I've added editorconfig to help us use a standardized way to write code. Feel free to change or update as you wish.
 - **Eslint**: Added, also, eslint to validate our code. Some fixes were made (parameters and variables not being used, and this kind of mistake).
   - Eslint will check ES6 for Tests, but ES5 for Main code. This is because UMD does not transpile to browser compatible code like Babel would be able to do.
   - New task added to npm/gulp: npm run lint / gulp lint
- **UMD**: the UMD pattern is included in the code by browserify. This way, we need to program Node-like and browserify makes it compatible with browsers. 
- **Tests**: Since the code changed to be Node-Like, I couldn't keep testing with Karma anymore since it runs tests against a browser and a browser does not recognize the "require" function, so... 
    - All tests were converted to Jest/jasmine syntax since Jest is the new tool to run the tests.
    - To execute the tests the command is the same as before : npm t

**Comment by lnfnunes** [comment]
Nice job @rmalveis !
I'm closing this issue.
